services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - docker-network
  
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - docker-network
    depends_on:
      - mysql
    command: php artisan queue:worker

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www.html
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - docker-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - docker-network

volumes:
  mysql-data:

networks:
  docker-network:
    driver: bridge